import React from 'react'
import type { AppDefinition } from './types'

// ─── App Components ────────────────────────────────────────────
import TerminalApp from './apps/Terminal'
import FinderApp from './apps/Finder'
import EditorApp from './apps/Editor'
import CalculatorApp from './apps/Calculator'
import ClockApp from './apps/Clock'
import SettingsApp from './apps/Settings'
import NotesApp from './apps/Notes'
import SafariApp from './apps/Safari'
import MusicApp from './apps/Music'
import CalendarApp from './apps/Calendar'
import MessagesApp from './apps/Messages'
import MailApp from './apps/Mail'
import PhotosApp from './apps/Photos'
import ContactsApp from './apps/Contacts'
import RemindersApp from './apps/Reminders'
import WeatherApp from './apps/Weather'
import MapsApp from './apps/Maps'
import FaceTimeApp from './apps/FaceTime'
import VideosApp from './apps/Videos'
import AboutApp from './apps/About'
import HelloPluginApp from './apps/HelloPlugin'
import PluginAdapter from './apps/PluginAdapter'

// 插件运行时包装（测试用，实际应从远程加载）
const wrapPlugin = (component: React.ComponentType<any>, id: string) =>
  () => React.createElement(PluginAdapter, { pluginComponent: component, pluginId: id, permissions: ['storage'] })

// ─── Icon Paths ────────────────────────────────────────────────
const icon = (name: string) => import.meta.env.BASE_URL + 'icons/' + name + '.png'
const iconSvg = (name: string) => import.meta.env.BASE_URL + 'icons/' + name + '.svg'

// ─── App Registry (ordered like macOS Dock) ────────────────────
export const apps: AppDefinition[] = [
  {
    id: 'finder',
    name: '访达',
    icon: icon('finder'),
    defaultSize: { width: 780, height: 480 },
    defaultPosition: { x: 60, y: 55 },
    component: FinderApp,
    menus: [
      { label: '访达', items: [
        { label: '关于访达', action: undefined },
        { type: 'divider' as const },
        { label: '设置…', shortcut: '⌘,', action: undefined },
        { label: '退出', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新建 Finder 窗口', shortcut: '⌘N', action: undefined },
        { label: '新建文件夹', shortcut: '⌘⇧N', action: undefined },
        { type: 'divider' as const },
        { label: '打开', shortcut: '⌘O', action: undefined },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { type: 'divider' as const },
        { label: '获取信息', shortcut: '⌘I', action: undefined },
        { label: '打印', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '图标视图', shortcut: '⌘1', action: undefined },
        { label: '列表视图', shortcut: '⌘2', action: undefined },
        { label: '分栏视图', shortcut: '⌘3', action: undefined },
        { label: 'Cover Flow', shortcut: '⌘4', action: undefined },
        { type: 'divider' as const },
        { label: '显示工具栏', shortcut: '⌘\\', action: undefined },
        { label: '显示路径栏', shortcut: '⌥⌘P', action: undefined },
        { label: '显示状态栏', shortcut: '⌘⇧P', action: undefined },
        { type: 'divider' as const },
        { label: '清理选择', shortcut: 'Escape', action: undefined },
        { label: '排列', action: undefined },
        { label: '整理', action: undefined },
      ]},
      { label: '前往', items: [
        { label: '退回', shortcut: '⌘[', action: undefined },
        { label: '前进', shortcut: '⌘]', action: undefined },
        { type: 'divider' as const },
        { label: '桌面', shortcut: '⇧⌘D', action: undefined },
        { label: '主目录', shortcut: '⇧⌘H', action: undefined },
        { label: '文稿', shortcut: '⇧⌘O', action: undefined },
        { label: '下载', shortcut: '⇧⌘J', action: undefined },
        { label: '应用程序', shortcut: '⇧⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '强制退出…', shortcut: '⌥⌘ESC', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '缩放', shortcut: '⌘Enter', action: undefined },
        { type: 'divider' as const },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
        { label: '拼合窗口', action: undefined },
        { label: '缩放至窗口', action: undefined },
        { label: '缩放至页宽', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '访达帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'safari',
    name: 'Safari',
    icon: icon('safari'),
    defaultSize: { width: 900, height: 560 },
    defaultPosition: { x: 80, y: 70 },
    component: SafariApp,
    menus: [
      { label: 'Safari', items: [
        { label: '关于 Safari', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '高级…', shortcut: '⌘Opt+P', action: undefined },
        { type: 'divider' as const },
        { label: '隐藏 Safari', shortcut: '⌘H', action: undefined },
        { label: '隐藏其他', shortcut: '⌘⌥H', action: undefined },
        { label: '退出 Safari', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新窗口', shortcut: '⌘N', action: undefined },
        { label: '新标签页', shortcut: '⌘T', action: undefined },
        { label: '从地址栏新建', shortcut: '⌘L', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '关闭标签页', shortcut: '⌘W', action: undefined },
        { type: 'divider' as const },
        { label: '打开文件…', shortcut: '⌘O', action: undefined },
        { label: '保存…', shortcut: '⌘S', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '导出为 PDF…', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '查找…', shortcut: '⌘F', action: undefined },
        { label: '查找下一个', shortcut: 'G', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '隐藏工具栏', shortcut: '⌘\\', action: undefined },
        { label: '隐藏地址栏', shortcut: '⇧⌘I', action: undefined },
        { label: '显示书签栏', shortcut: '⌥⌘B', action: undefined },
        { label: '显示阅读栏', shortcut: '⌥⌘R', action: undefined },
        { type: 'divider' as const },
        { label: '放大', shortcut: '⌘+', action: undefined },
        { label: '缩小', shortcut: '⌘-', action: undefined },
        { label: '实际大小', shortcut: '⌘0', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '历史记录', items: [
        { label: '清除历史记录…', action: undefined },
        { type: 'divider' as const },
        { label: '显示所有历史记录', shortcut: '⌘Y', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
        { type: 'divider' as const },
        { label: '拆分窗口', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: 'Safari 帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'messages',
    name: '信息',
    icon: icon('messages'),
    defaultSize: { width: 680, height: 480 },
    defaultPosition: { x: 100, y: 80 },
    component: MessagesApp,
    menus: [
      { label: '信息', items: [
        { label: '关于信息', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏信息', shortcut: '⌘H', action: undefined },
        { label: '退出信息', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新聊天', shortcut: '⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '信息', items: [
        { label: '个人名片…', action: undefined },
        { type: 'divider' as const },
        { label: '自动回复', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '隐藏工具栏', shortcut: '⌘\\', action: undefined },
        { label: '隐藏侧边栏', shortcut: '⌘⏎', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '信息帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'mail',
    name: '邮件',
    icon: icon('mail'),
    defaultSize: { width: 780, height: 520 },
    defaultPosition: { x: 120, y: 60 },
    component: MailApp,
    menus: [
      { label: '邮件', items: [
        { label: '关于邮件', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏邮件', shortcut: '⌘H', action: undefined },
        { label: '退出邮件', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新建邮件', shortcut: '⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { label: '导出为 PDF…', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '查找…', shortcut: '⌘F', action: undefined },
      ]},
      { label: '邮件', items: [
        { label: '发送邮件', shortcut: '⌘D', action: undefined },
        { label: '发送并等待送达通知', shortcut: '⌘⏎', action: undefined },
        { type: 'divider' as const },
        { label: '收件', shortcut: '⇧⌘I', action: undefined },
        { label: '全部收件', shortcut: '⌥⇧⌘I', action: undefined },
        { type: 'divider' as const },
        { label: '垃圾邮件', shortcut: '⌘⇧J', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '隐藏工具栏', shortcut: '⌘\\', action: undefined },
        { label: '隐藏地址栏', shortcut: '⇧⌘I', action: undefined },
        { label: '显示搜索栏', shortcut: '⌥⌘Y', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '邮件帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'calendar',
    name: '日历',
    icon: icon('calendar'),
    defaultSize: { width: 720, height: 500 },
    defaultPosition: { x: 140, y: 90 },
    component: CalendarApp,
    menus: [
      { label: '日历', items: [
        { label: '关于日历', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏日历', shortcut: '⌘H', action: undefined },
        { label: '退出日历', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新建日历…', shortcut: '⌘N', action: undefined },
        { label: '新建事件…', shortcut: '⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '日', shortcut: '⌘1', action: undefined },
        { label: '周', shortcut: '⌘2', action: undefined },
        { label: '月', shortcut: '⌘3', action: undefined },
        { label: '年', shortcut: '⌘4', action: undefined },
        { type: 'divider' as const },
        { label: '显示日程表', shortcut: '⇧⌘S', action: undefined },
        { label: '显示边栏', shortcut: '⌥⌘S', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '日历帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'maps',
    name: '地图',
    icon: icon('maps'),
    defaultSize: { width: 800, height: 520 },
    defaultPosition: { x: 80, y: 100 },
    component: MapsApp,
    menus: [
      { label: '地图', items: [
        { label: '关于地图', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏地图', shortcut: '⌘H', action: undefined },
        { label: '退出地图', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '地图类型…', action: undefined },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '地图帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'photos',
    name: '照片',
    icon: icon('photos'),
    defaultSize: { width: 860, height: 540 },
    defaultPosition: { x: 60, y: 70 },
    component: PhotosApp,
    menus: [
      { label: '照片', items: [
        { label: '关于照片', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏照片', shortcut: '⌘H', action: undefined },
        { label: '退出照片', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '导入…', shortcut: '⌘I', action: undefined },
        { label: '新建相簿…', shortcut: '⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { label: '导出…', action: undefined },
        { type: 'divider' as const },
        { label: '在访达中显示', shortcut: '⌘⇧R', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '删除', shortcut: '⌘Delete', action: undefined },
      ]},
      { label: '分享', items: [
        { label: '投屏到电视', shortcut: '⌘⇧T', action: undefined },
        { label: '在"屏幕共享"中查看', action: undefined },
        { type: 'divider' as const },
        { label: '用"邮件"发送', shortcut: '⌘⇧M', action: undefined },
        { label: '复制到"备忘录"', shortcut: '⌘⇧N', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '隐藏工具栏', shortcut: '⌘\\', action: undefined },
        { label: '显示隐藏媒体', shortcut: '⌘⇧.', action: undefined },
        { label: '显示缩略图', shortcut: '⌥⌘T', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '照片帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'face-time',
    name: '面部时光',
    icon: icon('facetime'),
    defaultSize: { width: 640, height: 460 },
    defaultPosition: { x: 200, y: 80 },
    component: FaceTimeApp,
    menus: [
      { label: '面部时光', items: [
        { label: '关于面部时光', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏面部时光', shortcut: '⌘H', action: undefined },
        { label: '退出面部时光', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新通话', shortcut: '⌘N', action: undefined },
        { label: '接受呼叫', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '接收音频', action: undefined },
        { label: '接收视频', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '面部时光帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'music',
    name: '音乐',
    icon: icon('music'),
    defaultSize: { width: 420, height: 520 },
    defaultPosition: { x: 300, y: 80 },
    component: MusicApp,
    menus: [
      { label: '音乐', items: [
        { label: '关于音乐', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏音乐', shortcut: '⌘H', action: undefined },
        { label: '退出音乐', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新增播放列表…', shortcut: '⌘N', action: undefined },
        { label: '新增文件夹播放列表…', shortcut: '⌘⇧N', action: undefined },
        { label: '新增智能播放列表…', shortcut: '⌥⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '导入', shortcut: '⌘I', action: undefined },
        { label: '将媒体库导入到 iPod…', action: undefined },
        { type: 'divider' as const },
        { label: '推出', shortcut: '⌘E', action: undefined },
        { label: '退出', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '显示隐藏歌词', shortcut: '⌘L', action: undefined },
      ]},
      { label: '库', items: [
        { label: '更新云库', shortcut: '⌘U', action: undefined },
        { label: '将曲库同步至 iCloud…', shortcut: '⌘⇧S', action: undefined },
        { type: 'divider' as const },
        { label: '显示重复项', shortcut: '⌘D', action: undefined },
        { label: '显示未使用的…', shortcut: '⌘⇧U', action: undefined },
      ]},
      { label: '商店', items: [
        { label: '打开 Apple Music…', shortcut: '⌘⇧K', action: undefined },
        { label: '更新 Apple Music', shortcut: '⌘⇧M', action: undefined },
        { type: 'divider' as const },
        { label: '查看我的账户…', shortcut: '⌘⌥A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '显示隐藏项目', shortcut: '⌘⇧.', action: undefined },
        { label: '显示歌词', shortcut: '⌘L', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '音乐帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'videos',
    name: '影片',
    icon: icon('movies'),
    defaultSize: { width: 780, height: 520 },
    defaultPosition: { x: 160, y: 90 },
    component: VideosApp,
    menus: [
      { label: '影片', items: [
        { label: '关于影片', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏影片', shortcut: '⌘H', action: undefined },
        { label: '退出影片', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '打开文件…', shortcut: '⌘O', action: undefined },
        { label: '打开网络流…', shortcut: '⌘U', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '在访达中显示', shortcut: '⌘⇧R', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '播放', items: [
        { label: '播放', shortcut: '⌘P', action: undefined },
        { label: '暂停', shortcut: '⌘L', action: undefined },
        { label: '停止', shortcut: '⌘.', action: undefined },
        { type: 'divider' as const },
        { label: '快退', shortcut: '⌘←', action: undefined },
        { label: '快进', shortcut: '⌘→', action: undefined },
        { type: 'divider' as const },
        { label: '循环播放', action: undefined },
        { label: '画中画', shortcut: '⌘⇧P', action: undefined },
      ]},
      { label: '查看', items: [
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
        { label: '退出全屏', shortcut: '⌘F', action: undefined },
        { type: 'divider' as const },
        { label: '真实大小', shortcut: '⌘0', action: undefined },
        { label: '放大', shortcut: '⌘+', action: undefined },
        { label: '缩小', shortcut: '⌘-', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '影片帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'notes',
    name: '备忘录',
    icon: icon('notes'),
    defaultSize: { width: 520, height: 380 },
    defaultPosition: { x: 200, y: 130 },
    component: NotesApp,
    menus: [
      { label: '备忘录', items: [
        { label: '关于备忘录', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏备忘录', shortcut: '⌘H', action: undefined },
        { label: '退出备忘录', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新备忘录', shortcut: '⌘N', action: undefined },
        { label: '新文件夹', shortcut: '⌘⇧N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '发送到「邮件」', shortcut: '⌘⇧M', action: undefined },
        { label: '发送到「信息」', shortcut: '⌘⇧I', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '删除', shortcut: '⌫', action: undefined },
        { type: 'divider' as const },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { label: '查找…', shortcut: '⌘F', action: undefined },
        { type: 'divider' as const },
        { label: '日期和时间', shortcut: '⌘;', action: undefined },
      ]},
      { label: '格式', items: [
        { label: '斜体', shortcut: '⌘I', action: undefined },
        { label: '加粗', shortcut: '⌘B', action: undefined },
        { label: '下划线', shortcut: '⌘U', action: undefined },
        { label: '删除线', shortcut: '⌘⇧-', action: undefined },
        { type: 'divider' as const },
        { label: '字体…', shortcut: '⌘T', action: undefined },
        { label: '字号', action: undefined },
      ]},
      { label: '查看', items: [
        { label: '文本格式', shortcut: '⌥⌘T', action: undefined },
        { label: '照片', shortcut: '⌥⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '备忘录帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'reminders',
    name: '提醒事项',
    icon: icon('reminders'),
    defaultSize: { width: 580, height: 440 },
    defaultPosition: { x: 220, y: 100 },
    component: RemindersApp,
    menus: [
      { label: '提醒事项', items: [
        { label: '关于提醒事项', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏提醒事项', shortcut: '⌘H', action: undefined },
        { label: '退出提醒事项', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新提醒事项列表', shortcut: '⌘N', action: undefined },
        { label: '新提醒事项', shortcut: '⌘N', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '完成', shortcut: '⌘D', action: undefined },
        { label: '删除', shortcut: '⌫', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '隐藏工具栏', shortcut: '⌘\\', action: undefined },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '提醒事项帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'contacts',
    name: '通讯录',
    icon: icon('contacts'),
    defaultSize: { width: 640, height: 460 },
    defaultPosition: { x: 180, y: 110 },
    component: ContactsApp,
    menus: [
      { label: '通讯录', items: [
        { label: '关于通讯录', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏通讯录', shortcut: '⌘H', action: undefined },
        { label: '退出通讯录', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新联系人', shortcut: '⌘N', action: undefined },
        { label: '新分组', shortcut: '⌘G', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '导入…', shortcut: '⌘I', action: undefined },
        { label: '导出…', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { type: 'divider' as const },
        { label: '查找联系人', shortcut: '⌘F', action: undefined },
      ]},
      { label: '显示', items: [
        { label: '群组视图', shortcut: '⌘1', action: undefined },
        { label: '列表视图', shortcut: '⌘2', action: undefined },
        { label: '卡片视图', shortcut: '⌘3', action: undefined },
        { type: 'divider' as const },
        { label: '显示隐藏字段', shortcut: '⌘⇧H', action: undefined },
        { label: '显示电子邮件', shortcut: '⌘⇧E', action: undefined },
        { label: '显示所有字段', shortcut: '⌘⇧A', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '通讯录帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'weather',
    name: '天气',
    icon: icon('weather'),
    defaultSize: { width: 560, height: 480 },
    defaultPosition: { x: 240, y: 70 },
    component: WeatherApp,
    menus: [
      { label: '天气', items: [
        { label: '关于天气', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏天气', shortcut: '⌘H', action: undefined },
        { label: '退出天气', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '查看', items: [
        { label: '华氏温度/摄氏度', shortcut: '⌘⇧T', action: undefined },
        { label: '英里/千米', shortcut: '⌘⇧M', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '天气帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'clock',
    name: '时钟',
    icon: icon('clock'),
    defaultSize: { width: 340, height: 420 },
    defaultPosition: { x: 380, y: 120 },
    component: ClockApp,
    menus: [
      { label: '时钟', items: [
        { label: '关于时钟', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏时钟', shortcut: '⌘H', action: undefined },
        { label: '退出时钟', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '世界时钟', shortcut: '⌘1', action: undefined },
        { label: '闹钟', shortcut: '⌘2', action: undefined },
        { label: '秒表', shortcut: '⌘3', action: undefined },
        { label: '计时器', shortcut: '⌘4', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '时钟帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'calculator',
    name: '计算器',
    icon: icon('calculator'),
    defaultSize: { width: 240, height: 360 },
    defaultPosition: { x: 400, y: 120 },
    component: CalculatorApp,
    menus: [
      { label: '计算器', items: [
        { label: '关于计算器', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏计算器', shortcut: '⌘H', action: undefined },
        { label: '退出计算器', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { type: 'divider' as const },
        { label: '清除', shortcut: 'Escape', action: undefined },
        { label: '全清', shortcut: '⌘⇧Clear', action: undefined },
      ]},
      { label: '查看', items: [
        { label: '标准', shortcut: '⌘1', action: undefined },
        { label: '数字转换器', shortcut: '⌘2', action: undefined },
        { label: '工程型', shortcut: '⌘3', action: undefined },
        { label: '程序员型', shortcut: '⌘4', action: undefined },
        { label: '统计型', shortcut: '⌘5', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '计算器帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'terminal',
    name: '终端',
    icon: iconSvg('terminal_dynamic'),
    defaultSize: { width: 680, height: 420 },
    defaultPosition: { x: 120, y: 90 },
    component: TerminalApp,
    menus: [
      { label: '终端', items: [
        { label: '关于终端', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '检查更新…', action: undefined },
        { type: 'divider' as const },
        { label: '隐藏终端', shortcut: '⌘H', action: undefined },
        { label: '退出终端', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新建窗口', shortcut: '⌘N', action: undefined },
        { label: '新建标签页', shortcut: '⌘T', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '关闭标签页', shortcut: '⌘W', action: undefined },
        { label: '分隔窗口', shortcut: '⌘D', action: undefined },
        { type: 'divider' as const },
        { label: '移动标签页', shortcut: '⌘⇧[', action: undefined },
        { label: '移到左边', shortcut: '⌘⇧]', action: undefined },
        { type: 'divider' as const },
        { label: '清屏', shortcut: '⌘K', action: undefined },
        { label: '重置窗口', shortcut: '⌘⇧R', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { label: '清除选区', shortcut: 'Escape', action: undefined },
        { type: 'divider' as const },
        { label: '查找…', shortcut: '⌘F', action: undefined },
        { label: '上一个查找项', shortcut: '⌘G', action: undefined },
        { label: '下一个查找项', shortcut: '⌘⇧G', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '放大', shortcut: '⌘+', action: undefined },
        { label: '缩小', shortcut: '⌘-', action: undefined },
        { label: '实际大小', shortcut: '⌘0', action: undefined },
        { type: 'divider' as const },
        { label: '标准字体', shortcut: '⌘S', action: undefined },
        { label: '等宽字体', shortcut: '⌘L', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: 'Shell', items: [
        { label: '创建窗口…', shortcut: '⌘N', action: undefined },
        { label: '创建标签页…', shortcut: '⌘T', action: undefined },
        { type: 'divider' as const },
        { label: '运行命令…', action: undefined },
        { label: '输入内容…', action: undefined },
        { type: 'divider' as const },
        { label: '更改工作目录…', action: undefined },
        { label: '新建远程连接…', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '缩放', shortcut: '⌘Enter', action: undefined },
        { type: 'divider' as const },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
        { label: '拼合窗口', action: undefined },
        { label: '缩放窗口', action: undefined },
        { label: '缩放标签页', action: undefined },
        { type: 'divider' as const },
        { label: '移动至左边空间', shortcut: '⌘⇧[', action: undefined },
        { label: '移动至右边空间', shortcut: '⌘⇧]', action: undefined },
        { label: '前一个标签页', shortcut: '⌘{', action: undefined },
        { label: '后一个标签页', shortcut: '⌘}', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '终端帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'editor',
    name: '文本编辑',
    icon: icon('textedit'),
    defaultSize: { width: 720, height: 500 },
    defaultPosition: { x: 160, y: 110 },
    component: EditorApp,
    menus: [
      { label: '文本编辑', items: [
        { label: '关于文本编辑', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置…', shortcut: '⌘,', action: undefined },
        { label: '隐藏文本编辑', shortcut: '⌘H', action: undefined },
        { label: '退出文本编辑', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '新建', shortcut: '⌘N', action: undefined },
        { label: '打开…', shortcut: '⌘O', action: undefined },
        { label: '从文件夹选取…', shortcut: '⌘⇧O', action: undefined },
        { type: 'divider' as const },
        { label: '另存为…', shortcut: '⌘S', action: undefined },
        { label: '导出…', action: undefined },
        { type: 'divider' as const },
        { label: '打印…', shortcut: '⌘P', action: undefined },
        { type: 'divider' as const },
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '退出', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '删除', shortcut: '⌫', action: undefined },
        { type: 'divider' as const },
        { label: '全选', shortcut: '⌘A', action: undefined },
        { label: '查找…', shortcut: '⌘F', action: undefined },
        { label: '替换…', shortcut: '⌥⌘F', action: undefined },
        { label: '再次查找…', shortcut: '⌘G', action: undefined },
        { label: '再次替换', shortcut: '⌥⌘G', action: undefined },
      ]},
      { label: '格式', items: [
        { label: '设为段落', shortcut: '⌘↵', action: undefined },
        { label: '字体…', shortcut: '⌘T', action: undefined },
        { type: 'divider' as const },
        { label: '加粗', shortcut: '⌘B', action: undefined },
        { label: '斜体', shortcut: '⌘I', action: undefined },
        { label: '下划线', shortcut: '⌘U', action: undefined },
        { type: 'divider' as const },
        { label: '增大字号', shortcut: '⌘]', action: undefined },
        { label: '减小字号', shortcut: '⌘[', action: undefined },
      ]},
      { label: '查看', items: [
        { label: '实际大小', shortcut: '⌘0', action: undefined },
        { label: '放大', shortcut: '⌘+', action: undefined },
        { label: '缩小', shortcut: '⌘-', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '缩放', shortcut: '⌘Enter', action: undefined },
        { type: 'divider' as const },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '文本编辑帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'settings',
    name: '系统设置',
    icon: icon('settings'),
    defaultSize: { width: 680, height: 460 },
    defaultPosition: { x: 140, y: 90 },
    component: SettingsApp,
    menus: [
      { label: '系统设置', items: [
        { label: '关于本机', action: undefined },
        { type: 'divider' as const },
        { label: '更多偏好设置…', action: undefined },
        { label: '隐藏系统设置', shortcut: '⌘H', action: undefined },
        { label: '退出系统设置', shortcut: '⌘Q', action: undefined },
      ]},
      { label: '文件', items: [
        { label: '关闭窗口', shortcut: '⌘W', action: undefined },
        { label: '打印…', shortcut: '⌘P', action: undefined },
      ]},
      { label: '编辑', items: [
        { label: '撤销', shortcut: '⌘Z', action: undefined },
        { label: '重做', shortcut: '⇧⌘Z', action: undefined },
        { type: 'divider' as const },
        { label: '剪切', shortcut: '⌘X', action: undefined },
        { label: '复制', shortcut: '⌘C', action: undefined },
        { label: '粘贴', shortcut: '⌘V', action: undefined },
        { label: '全选', shortcut: '⌘A', action: undefined },
      ]},
      { label: '视图', items: [
        { label: '侧边栏', shortcut: '⌥⌘S', action: undefined },
        { type: 'divider' as const },
        { label: '进入全屏', shortcut: '⌘⌫', action: undefined },
      ]},
      { label: '窗口', items: [
        { label: '最小化', shortcut: '⌘M', action: undefined },
        { label: '前置全部', shortcut: '⌘`', action: undefined },
      ]},
      { label: '帮助', items: [
        { label: '系统设置帮助', shortcut: '⌘?', action: undefined },
      ]},
    ],
  },
  {
    id: 'about',
    name: '关于本机',
    icon: icon('settings'),
    defaultSize: { width: 460, height: 520 },
    defaultPosition: { x: window.innerWidth / 2 - 230, y: window.innerHeight / 2 - 260 },
    component: AboutApp,
    menus: [
      { label: '关于本机', items: [
        { label: '关闭', shortcut: '⌘W', action: undefined },
      ]},
    ],
  },
  // ─── 插件应用（测试用）────────────────────────────────────────────
  {
    id: 'hello-plugin',
    name: 'Hello Plugin',
    icon: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImciIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPjxzdG9wIG9mZnNldD0iMCUiIHN0b3AtY29sb3I9IiM2NjdlZWEiLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiM3NjRiYTIiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48cmVjdCB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCIgcng9IjI4IiBmaWxsPSJ1cmwoI2cpIi8+PHRleHQgeD0iNjQiIHk9Ijg2IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmb250LXNpemU9IjcyIiBmb250LWZhbWlseT0iLWFwcGxlLXN5c3RlbSxzYW5zLXNlcmlmIiBmaWxsPSIjZmZmIj7wn5q9PC90ZXh0Pjwvc3ZnPg==',
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 120, y: 90 },
    component: wrapPlugin(HelloPluginApp, 'hello-plugin'),
    menus: [
      { label: 'Hello Plugin', items: [
        { label: '关于', action: undefined },
        { type: 'divider' as const },
        { label: '偏好设置', action: undefined },
        { type: 'divider' as const },
        { label: '退出', shortcut: '⌘W', action: undefined },
      ]},
    ],
  },
]
